### PR TITLE
Added additional switch entity id HA attribute on controller and zone binary_sensor, and amended documentation thereto

### PR DESCRIPTION
**Pull request by evercape**
Hi Robert,

Although I don't know python at all, I had a go at including switch entities objects as attributes on the controller and zone binary object.

Feel free to accept the pull request if you feel this adds value and saves you some time.

Have added the constant for the attribute label, 2 similar functions to JSON encode the controller and zone switch entity object and to then called those functions just prior to the 'user/more' attribute that you recently added. 

I also noticed that there seems to be another parameter show:config: true which, similarly to show:timeline:true outputs some configuration data. Have taken the liberty to amend documentation 5.4 accordingly. 

I did not want to mess with the controller's and zone's configuration objects hence opted for a separate attribute to expose the switch entities. An alternative way of doing this to include the switch entities in the configuration data. 

Thanks again for an amazing integration, which allows me to learn a lot about HA and even some python copy/paste/amend ;-).

Cheers
Martin

### CODE REVIEW

**Comment by rgc99** [comment]
I think the zone configuration might be a better place as it's already JSON formatted. I don't see any problem including in this stream. BTW have you looked at the irrigation_unlimited.coordinator entity?

**Comment by evercape** [comment]
> I think the zone configuration might be a better place as it's already JSON formatted. I don't see any problem including in this stream. BTW have you looked at the irrigation_unlimited.coordinator entity?

Hi Robert, have done so. Please feel free to update. Hope I have done it correctly. I checked it and its working see screenshot.
Settings_–_Home_Assistant

**Comment by evercape** [comment]
> BTW have you looked at the irrigation_unlimited.coordinator entity?

I tried to add there but wasn't successful. I think it is useful on zones, if you want to add to controller also great then all in one place.

I am currently looking at the forward scheduling basically creating one object/json array with all upcoming zones' timelines. If I have that I then can use that in some automation to temporarily pause and resume. I still think this is something important to consider, in particular when ie flow rate or pressure drops or something else happens. 

Most importantly, learning a bit of python, and thanks god for chat gpt ;-)

**Comment by rgc99** [comment]
I cherry picked my way through this. Just left the switch entities in the configuration data and not as an attribute. I would prefer it this way unless you really need it as an attribute on the zone. The configuration data is the area that developers can switch on to expose more information - thanks for documenting it.

**Comment by evercape** [comment]
> Just left the switch entities in the configuration data and not as an attribute.

That is of course perfectly fine Robert, fully agree. There is always the `more:` [attribute/object](https://github.com/rgc99/irrigation_unlimited#511-more-object), if one needs to pass from yaml to attribute...

I will hopefully be able to resolve the conflict in branches now, first time properly working with GitHub.

If you need any help with documentation/translation, always happy to support. I am an old and old school database guy, and python, C++ definitely not my strength :-)

On another note, how often do you publish versions (that then work via HACS)? I like that HA does monthly major releases, and 2-3 times a month minor bugfix updates. I run HA on Proxmox VM, with limited file system/FTP access and have resorted to manual copy & paste of files to make updates. Not very efficient, so a HACS update of a newer version would be quiet useful.

**Comment by rgc99** [comment]
I meant the switch_entities are in the JSON configuration attribute in the zone sensor.

Good to know you have a computing background. This was my first significant python project, bit of a learning curve.

Funny you should mention a new release. I was just in the throws of it. Usually at the beginning of the  month if there are some worthwhile updates. Stay tuned.

**Comment by evercape** [comment]
> I meant the switch_entities are in the JSON configuration attribute in the zone sensor.

got that, so there are now at least two ways of dealing with that. thanks for including it!
 
> Good to know you have a computing background. This was my first significant python project, bit of a learning curve.

well done - it is amazing. Last night, I have setup a test/dev VM HA on proxmox so I can play around/learn without breaking the main instance. Still need to figure out how to do proper python dev with HA, a bit annoying for every change to re-start HA.

> Funny you should mention a new release. 

Thanks for the new release. does not show in HACS yet as an update but will probably do soon. Anyways, all good.

**Pull request closed without merging**
